
version: '3.8'
services:
  code-server:
    container_name: code-serverv1
    build:
      context: .
      args:
        BASE: ${BASE}
        VERSION: ${VERSION}
        DISTRO: ${DISTRO}
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    ports:
      - 8080:8080
      - 3000:3000
      - 5173:5173
      - 4173:4173
      - 6006:6006
    environment:
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    volumes:
      - ./:/home/coder/project
      - code-server-config:/home/coder/.config
      - ssh-keys:/home/coder/.ssh
volumes:
  #code-data:
  code-server-config:
    external: true
  ssh-keys:
    external: true
